# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nWidgets.ui',
# licensing of 'nWidgets.ui' applies.
#
# Created: Thu Mar 14 18:07:20 2019
#      by: pyside2-uic  running on PySide2 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(940, 697)
        MainWindow.setMinimumSize(QtCore.QSize(729, 468))
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_9.addWidget(self.line)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.graphicsView = QtWidgets.QGraphicsView(self.frame_3)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout_3.addWidget(self.graphicsView)
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_5 = QtWidgets.QGroupBox(self.frame_4)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_8.setSpacing(9)
        self.verticalLayout_8.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pushButton_16 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_16.setObjectName("pushButton_16")
        self.verticalLayout_8.addWidget(self.pushButton_16)
        self.pushButton_17 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_17.setObjectName("pushButton_17")
        self.verticalLayout_8.addWidget(self.pushButton_17)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_8.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_8.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout_8.addWidget(self.checkBox_4)
        self.verticalLayout_5.addWidget(self.groupBox_5)
        spacerItem = QtWidgets.QSpacerItem(20, 97, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.groupBox_6 = QtWidgets.QGroupBox(self.frame_4)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton_15 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_15.setObjectName("pushButton_15")
        self.verticalLayout_7.addWidget(self.pushButton_15)
        self.pushButton_14 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_14.setObjectName("pushButton_14")
        self.verticalLayout_7.addWidget(self.pushButton_14)
        self.verticalLayout_5.addWidget(self.groupBox_6)
        self.horizontalLayout_3.addWidget(self.frame_4)
        self.verticalLayout_9.addWidget(self.frame_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 940, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuUDP_Controls = QtWidgets.QMenu(self.menuSettings)
        self.menuUDP_Controls.setObjectName("menuUDP_Controls")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget_6 = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget_6.sizePolicy().hasHeightForWidth())
        self.dockWidget_6.setSizePolicy(sizePolicy)
        self.dockWidget_6.setMinimumSize(QtCore.QSize(450, 105))
        self.dockWidget_6.setMaximumSize(QtCore.QSize(450, 105))
        self.dockWidget_6.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable|QtWidgets.QDockWidget.DockWidgetVerticalTitleBar)
        self.dockWidget_6.setAllowedAreas(QtCore.Qt.TopDockWidgetArea)
        self.dockWidget_6.setObjectName("dockWidget_6")
        self.dockWidgetContents_7 = QtWidgets.QWidget()
        self.dockWidgetContents_7.setObjectName("dockWidgetContents_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.dockWidgetContents_7)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_7 = QtWidgets.QPushButton(self.dockWidgetContents_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_4.addWidget(self.pushButton_7)
        self.groupBox_2 = QtWidgets.QGroupBox(self.dockWidgetContents_7)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.dockWidgetContents_7)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.groupBox)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.groupBox)
        self.frame_2.setMinimumSize(QtCore.QSize(50, 0))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_4.addWidget(self.label_11)
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10)
        self.horizontalLayout.addWidget(self.frame_2)
        self.horizontalLayout_4.addWidget(self.groupBox)
        self.groupBox_4 = QtWidgets.QGroupBox(self.dockWidgetContents_7)
        self.groupBox_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_6.setSpacing(3)
        self.verticalLayout_6.setContentsMargins(2, 0, 2, 10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_6.addWidget(self.pushButton_3)
        self.horizontalLayout_4.addWidget(self.groupBox_4)
        self.dockWidget_6.setWidget(self.dockWidgetContents_7)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.dockWidget_6)
        self.dockWidget_8 = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget_8.sizePolicy().hasHeightForWidth())
        self.dockWidget_8.setSizePolicy(sizePolicy)
        self.dockWidget_8.setMinimumSize(QtCore.QSize(374, 130))
        self.dockWidget_8.setMaximumSize(QtCore.QSize(524287, 130))
        self.dockWidget_8.setBaseSize(QtCore.QSize(0, 0))
        self.dockWidget_8.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.dockWidget_8.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea)
        self.dockWidget_8.setObjectName("dockWidget_8")
        self.dockWidgetContents_9 = QtWidgets.QWidget()
        self.dockWidgetContents_9.setObjectName("dockWidgetContents_9")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents_9)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.dockWidgetContents_9)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.dockWidgetContents_9)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 1, 2, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.dockWidgetContents_9)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 1, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 1, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.dockWidgetContents_9)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 1, 5, 1, 1)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.dockWidgetContents_9)
        self.plainTextEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.plainTextEdit.setSizeIncrement(QtCore.QSize(0, 0))
        self.plainTextEdit.setBaseSize(QtCore.QSize(0, 0))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 0, 0, 1, 6)
        self.dockWidget_8.setWidget(self.dockWidgetContents_9)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget_8)
        self.dockWidget_2 = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget_2.sizePolicy().hasHeightForWidth())
        self.dockWidget_2.setSizePolicy(sizePolicy)
        self.dockWidget_2.setMinimumSize(QtCore.QSize(240, 94))
        self.dockWidget_2.setMaximumSize(QtCore.QSize(240, 524287))
        self.dockWidget_2.setFeatures(QtWidgets.QDockWidget.DockWidgetFeatureMask)
        self.dockWidget_2.setAllowedAreas(QtCore.Qt.TopDockWidgetArea)
        self.dockWidget_2.setObjectName("dockWidget_2")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.dockWidgetContents_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.dockWidgetContents_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.pushButton_12.sizePolicy().hasHeightForWidth())
        self.pushButton_12.setSizePolicy(sizePolicy)
        self.pushButton_12.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_12.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_5.addWidget(self.pushButton_12)
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_13.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_13.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_5.addWidget(self.pushButton_13)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_5.addWidget(self.pushButton)
        self.pushButton_18 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_18.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_18.setObjectName("pushButton_18")
        self.horizontalLayout_5.addWidget(self.pushButton_18)
        self.horizontalLayout_2.addWidget(self.groupBox_3)
        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.dockWidget_2)
        self.actionBegin = QtWidgets.QAction(MainWindow)
        self.actionBegin.setObjectName("actionBegin")
        self.actionExperiment = QtWidgets.QAction(MainWindow)
        self.actionExperiment.setCheckable(True)
        self.actionExperiment.setObjectName("actionExperiment")
        self.actionParameters = QtWidgets.QAction(MainWindow)
        self.actionParameters.setCheckable(True)
        self.actionParameters.setObjectName("actionParameters")
        self.actionLive_Data = QtWidgets.QAction(MainWindow)
        self.actionLive_Data.setCheckable(True)
        self.actionLive_Data.setObjectName("actionLive_Data")
        self.actionConfigure_Data_Buddy = QtWidgets.QAction(MainWindow)
        self.actionConfigure_Data_Buddy.setObjectName("actionConfigure_Data_Buddy")
        self.actionAbout_RS_Companion = QtWidgets.QAction(MainWindow)
        self.actionAbout_RS_Companion.setObjectName("actionAbout_RS_Companion")
        self.actionAbout_Red_Scientific = QtWidgets.QAction(MainWindow)
        self.actionAbout_Red_Scientific.setObjectName("actionAbout_Red_Scientific")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionRaw_Serial = QtWidgets.QAction(MainWindow)
        self.actionRaw_Serial.setObjectName("actionRaw_Serial")
        self.actionExit_2 = QtWidgets.QAction(MainWindow)
        self.actionExit_2.setObjectName("actionExit_2")
        self.actionDisplay_Tooltips = QtWidgets.QAction(MainWindow)
        self.actionDisplay_Tooltips.setObjectName("actionDisplay_Tooltips")
        self.actionConfigure = QtWidgets.QAction(MainWindow)
        self.actionConfigure.setObjectName("actionConfigure")
        self.actionCOM_Port = QtWidgets.QAction(MainWindow)
        self.actionCOM_Port.setObjectName("actionCOM_Port")
        self.actionOutput = QtWidgets.QAction(MainWindow)
        self.actionOutput.setObjectName("actionOutput")
        self.actionInput = QtWidgets.QAction(MainWindow)
        self.actionInput.setObjectName("actionInput")
        self.menuFile.addAction(self.actionBegin)
        self.menuFile.addAction(self.actionExit)
        self.menuView.addAction(self.actionRaw_Serial)
        self.menuView.addAction(self.actionExperiment)
        self.menuView.addAction(self.actionConfigure)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionDisplay_Tooltips)
        self.menuHelp.addAction(self.actionAbout_RS_Companion)
        self.menuHelp.addAction(self.actionAbout_Red_Scientific)
        self.menuUDP_Controls.addAction(self.actionOutput)
        self.menuUDP_Controls.addAction(self.actionInput)
        self.menuSettings.addAction(self.actionCOM_Port)
        self.menuSettings.addAction(self.menuUDP_Controls.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.pushButton_6, QtCore.SIGNAL("clicked()"), self.plainTextEdit.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "RS Device Companion", None, -1))
        self.groupBox_5.setTitle(QtWidgets.QApplication.translate("MainWindow", "GroupBox", None, -1))
        self.pushButton_16.setText(QtWidgets.QApplication.translate("MainWindow", "PushButton", None, -1))
        self.pushButton_17.setText(QtWidgets.QApplication.translate("MainWindow", "PushButton", None, -1))
        self.checkBox_2.setText(QtWidgets.QApplication.translate("MainWindow", "CheckBox", None, -1))
        self.checkBox_3.setText(QtWidgets.QApplication.translate("MainWindow", "CheckBox", None, -1))
        self.checkBox_4.setText(QtWidgets.QApplication.translate("MainWindow", "CheckBox", None, -1))
        self.groupBox_6.setTitle(QtWidgets.QApplication.translate("MainWindow", "GroupBox", None, -1))
        self.pushButton_15.setText(QtWidgets.QApplication.translate("MainWindow", "PushButton", None, -1))
        self.pushButton_14.setText(QtWidgets.QApplication.translate("MainWindow", "PushButton", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.menuView.setTitle(QtWidgets.QApplication.translate("MainWindow", "Window", None, -1))
        self.menuHelp.setTitle(QtWidgets.QApplication.translate("MainWindow", "Help", None, -1))
        self.menuSettings.setTitle(QtWidgets.QApplication.translate("MainWindow", "Settings", None, -1))
        self.menuUDP_Controls.setTitle(QtWidgets.QApplication.translate("MainWindow", "UDP Controls", None, -1))
        self.dockWidget_6.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Control", None, -1))
        self.pushButton_7.setText(QtWidgets.QApplication.translate("MainWindow", "Run\n"
"Trial", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "Key Flag", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("MainWindow", "NA", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Timing", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Trial:", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Experiment:", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("MainWindow", "NA", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("MainWindow", "NA", None, -1))
        self.groupBox_4.setTitle(QtWidgets.QApplication.translate("MainWindow", "File Directory", None, -1))
        self.pushButton_3.setText(QtWidgets.QApplication.translate("MainWindow", "Open", None, -1))
        self.dockWidget_8.setToolTip(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>Displays all communications with Red Scientific Hardware. These can be saved for later browsing and debugging.</p></body></html>", None, -1))
        self.dockWidget_8.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "COM", None, -1))
        self.pushButton_2.setToolTip(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>Saves all raw COM messages to your data folder.</p></body></html>", None, -1))
        self.pushButton_2.setText(QtWidgets.QApplication.translate("MainWindow", "Record", None, -1))
        self.pushButton_5.setToolTip(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>Freezes the auto scrolling of COM messages.</p></body></html>", None, -1))
        self.pushButton_5.setText(QtWidgets.QApplication.translate("MainWindow", "Freeze", None, -1))
        self.pushButton_6.setToolTip(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>Clears all COM messages in the pane above.</p></body></html>", None, -1))
        self.pushButton_6.setText(QtWidgets.QApplication.translate("MainWindow", "Clear", None, -1))
        self.checkBox.setText(QtWidgets.QApplication.translate("MainWindow", "CheckBox", None, -1))
        self.dockWidget_2.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Configure", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("MainWindow", "Red Scientific Devices", None, -1))
        self.pushButton_12.setText(QtWidgets.QApplication.translate("MainWindow", "A", None, -1))
        self.pushButton_13.setText(QtWidgets.QApplication.translate("MainWindow", "B", None, -1))
        self.pushButton.setText(QtWidgets.QApplication.translate("MainWindow", "C", None, -1))
        self.pushButton_18.setText(QtWidgets.QApplication.translate("MainWindow", "D", None, -1))
        self.actionBegin.setText(QtWidgets.QApplication.translate("MainWindow", "Begin Experiment", None, -1))
        self.actionBegin.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Begin Experiment", None, -1))
        self.actionExperiment.setText(QtWidgets.QApplication.translate("MainWindow", "COM Messages", None, -1))
        self.actionParameters.setText(QtWidgets.QApplication.translate("MainWindow", "Parameters", None, -1))
        self.actionLive_Data.setText(QtWidgets.QApplication.translate("MainWindow", "Live Data", None, -1))
        self.actionConfigure_Data_Buddy.setText(QtWidgets.QApplication.translate("MainWindow", "Configure Data Buddy", None, -1))
        self.actionAbout_RS_Companion.setText(QtWidgets.QApplication.translate("MainWindow", "About RS Companion", None, -1))
        self.actionAbout_Red_Scientific.setText(QtWidgets.QApplication.translate("MainWindow", "About Red Scientific", None, -1))
        self.actionExit.setText(QtWidgets.QApplication.translate("MainWindow", "End Experiment", None, -1))
        self.actionRaw_Serial.setText(QtWidgets.QApplication.translate("MainWindow", "Trial Controls", None, -1))
        self.actionExit_2.setText(QtWidgets.QApplication.translate("MainWindow", "Exit", None, -1))
        self.actionDisplay_Tooltips.setText(QtWidgets.QApplication.translate("MainWindow", "Display Tooltips", None, -1))
        self.actionConfigure.setText(QtWidgets.QApplication.translate("MainWindow", "Configure", None, -1))
        self.actionCOM_Port.setText(QtWidgets.QApplication.translate("MainWindow", "COM Port", None, -1))
        self.actionOutput.setText(QtWidgets.QApplication.translate("MainWindow", "Output", None, -1))
        self.actionInput.setText(QtWidgets.QApplication.translate("MainWindow", "Input", None, -1))

